// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player-movement.proto

#ifndef PROTOBUF_player_2dmovement_2eproto__INCLUDED
#define PROTOBUF_player_2dmovement_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_player_2dmovement_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPlayerMovementImpl();
void InitDefaultsPlayerMovement();
inline void InitDefaults() {
  InitDefaultsPlayerMovement();
}
}  // namespace protobuf_player_2dmovement_2eproto
class PlayerMovement;
class PlayerMovementDefaultTypeInternal;
extern PlayerMovementDefaultTypeInternal _PlayerMovement_default_instance_;

// ===================================================================

class PlayerMovement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PlayerMovement) */ {
 public:
  PlayerMovement();
  virtual ~PlayerMovement();

  PlayerMovement(const PlayerMovement& from);

  inline PlayerMovement& operator=(const PlayerMovement& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlayerMovement(PlayerMovement&& from) noexcept
    : PlayerMovement() {
    *this = ::std::move(from);
  }

  inline PlayerMovement& operator=(PlayerMovement&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerMovement& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerMovement* internal_default_instance() {
    return reinterpret_cast<const PlayerMovement*>(
               &_PlayerMovement_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PlayerMovement* other);
  friend void swap(PlayerMovement& a, PlayerMovement& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlayerMovement* New() const PROTOBUF_FINAL { return New(NULL); }

  PlayerMovement* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PlayerMovement& from);
  void MergeFrom(const PlayerMovement& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PlayerMovement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // int32 hash = 2;
  void clear_hash();
  static const int kHashFieldNumber = 2;
  ::google::protobuf::int32 hash() const;
  void set_hash(::google::protobuf::int32 value);

  // int32 x = 3;
  void clear_x();
  static const int kXFieldNumber = 3;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // int32 y = 4;
  void clear_y();
  static const int kYFieldNumber = 4;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // int32 z = 5;
  void clear_z();
  static const int kZFieldNumber = 5;
  ::google::protobuf::int32 z() const;
  void set_z(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PlayerMovement)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::int32 hash_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 z_;
  mutable int _cached_size_;
  friend struct ::protobuf_player_2dmovement_2eproto::TableStruct;
  friend void ::protobuf_player_2dmovement_2eproto::InitDefaultsPlayerMovementImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlayerMovement

// string id = 1;
inline void PlayerMovement::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PlayerMovement::id() const {
  // @@protoc_insertion_point(field_get:PlayerMovement.id)
  return id_.GetNoArena();
}
inline void PlayerMovement::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PlayerMovement.id)
}
#if LANG_CXX11
inline void PlayerMovement::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PlayerMovement.id)
}
#endif
inline void PlayerMovement::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PlayerMovement.id)
}
inline void PlayerMovement::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PlayerMovement.id)
}
inline ::std::string* PlayerMovement::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:PlayerMovement.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PlayerMovement::release_id() {
  // @@protoc_insertion_point(field_release:PlayerMovement.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerMovement::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:PlayerMovement.id)
}

// int32 hash = 2;
inline void PlayerMovement::clear_hash() {
  hash_ = 0;
}
inline ::google::protobuf::int32 PlayerMovement::hash() const {
  // @@protoc_insertion_point(field_get:PlayerMovement.hash)
  return hash_;
}
inline void PlayerMovement::set_hash(::google::protobuf::int32 value) {
  
  hash_ = value;
  // @@protoc_insertion_point(field_set:PlayerMovement.hash)
}

// int32 x = 3;
inline void PlayerMovement::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 PlayerMovement::x() const {
  // @@protoc_insertion_point(field_get:PlayerMovement.x)
  return x_;
}
inline void PlayerMovement::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:PlayerMovement.x)
}

// int32 y = 4;
inline void PlayerMovement::clear_y() {
  y_ = 0;
}
inline ::google::protobuf::int32 PlayerMovement::y() const {
  // @@protoc_insertion_point(field_get:PlayerMovement.y)
  return y_;
}
inline void PlayerMovement::set_y(::google::protobuf::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:PlayerMovement.y)
}

// int32 z = 5;
inline void PlayerMovement::clear_z() {
  z_ = 0;
}
inline ::google::protobuf::int32 PlayerMovement::z() const {
  // @@protoc_insertion_point(field_get:PlayerMovement.z)
  return z_;
}
inline void PlayerMovement::set_z(::google::protobuf::int32 value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:PlayerMovement.z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_player_2dmovement_2eproto__INCLUDED
